### ISSUE TITLE
Removed from wordpress.org?

### ISSUE THREAD

**Issue by ryanwryan** [pixolin/scroll-to-anchor#9]
Hello,
I read a notice today on my wordfence plugin that scroll-to-anchor has been removed from wordpress.org and led me to this page -

https://www.wordfence.com/help/scan/scan-results/?utm_source=plugin&utm_medium=pluginUI&utm_campaign=docsIcon#plugin-removed

This is a great plugin, and I have used it for awhile now. Do you have any input regarding this?

Thank you!

**Comment by pixolin** [comment]
I asked the WordPress plugin team to remove my plugin from the plugin directory, as the plugin is deprecated with WordPress 5.0 and I don’t have resources to refactor it.

The idea behind the plugin was to simplify the process of adding anchors by adding a formatting icon in the TinyMCE-toolbar, which is obsolete with the new editor. The plugin also inserted shortcodes, which would still work, but should have been replaced by blocks.

I see no (security) reason not to use the plugin if you use WordPress < 5.0 or use the Classic Editor plugin, but you should try to find a new plugin which supports blocks for the future.

Regarding informations on removed plugins, Sergej Müller added a bug ticket ["Dashboard alert if a plugin was removed from WordPress plugins repo"](https://core.trac.wordpress.org/ticket/30465) a while ago, which was closed as "Won't fix" for various reasons. While WordFence's alert on removed plugins at least informs users, it also raises concerns that the removal was due to security issues, which certainly isn't the case her.

**Comment by ryanwryan** [comment]
I understand, thank you for such a detailed response. I greatly appreciate it.

**Comment by pixolin** [comment]
Happy to help.
